### PR TITLE
SPI Register Interface - Initial definition using RGB LED

### PR DESCRIPTION
**Pull request by aentinger**

### CODE REVIEW

**Comment by aentinger** [comment]
Hi @generationmake :wave: A revision register certainly is a good idea. However, I don't share your concern regarding overwriting the register with 0. This is the pretty standard to access any type of register based IO device, that is an address byte followed by a value byte in case of write and a address byte followed by any value which is ignored by the logic in the FPGA and instead the content of the register is clocked out on MISO. What I did indeed forget is to **mark** the address byte with a read/write flag.

**Read**
```
MOSI | Register Address | Any Value      |
MISO | 0                | Register Value |
```
**Write**
```
MOSI | 0x80 | Register Address  | Register Value |
MISO | 0                        | 0              |
```

**Comment by aentinger** [comment]
Hi @generationmake :wave: I've added a read-only register containing the FPGA revision number as well as explained via diagram how I imagine a read/write access should look like. What do you think?

**Comment by aentinger** [comment]
Hi @generationmake :wave: I did merge this PR pre-maturely in order to demonstrate to someone how to use the git workflow. I'm still very interested in hearing your feedback and incorporating it into future work.

**Comment by generationmake** [comment]
Hi @aentinger The updated register definition with the write flag seems to be OK now. This is what was missing in the first draft.
To improve code robustness you could also mask out the write bit in the read access function.

The revision register seems to be OK. We will have to see how long the 8 bits of the register last.

**Pull request merged**
